/* for CART */
export const GET_PRODUCTS_FROM_LOCALSTORAGE_REQUEST = "CART/GET_PRODUCTS_FROM_LOCALSTORAGE_REQUEST"
export const GET_PRODUCTS_FROM_LOCALSTORAGE_SUCCESS = "CART/GET_PRODUCTS_FROM_LOCALSTORAGE_SUCCESS"

export const GET_DETAILED_PRODUCTS_REQUEST = "CART/GET_DETAILED_PRODUCTS_REQUEST"
export const GET_DETAILED_PRODUCTS_SUCCESS = "CART/GET_DETAILED_PRODUCTS_SUCCESS"

export const ADD_TO_CART_REQUEST = "CART/ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "CART/ADD_TO_CART_SUCCESS"

export const REMOVE_FROM_CART_REQUEST = "CART/REMOVE_TO_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "CART/REMOVE_TO_CART_SUCCESS"

export const CHANGE_CNT_REQUEST = "CART/CHANGE_CNT_REQUEST"
export const CHANGE_CNT_SUCCESS = "CART/CHANGE_CNT_SUCCESS"

/* for TELEVISIONS */
export const GET_TELEVISIONS_REQUEST = "TELEVISIONS/GET_TELEVISIONS_REQUEST"
export const GET_TELEVISIONS_SUCCESS = "TELEVISIONS/GET_TELEVISIONS_SUCCESS"
export const GET_TELEVISIONS_FAIL = "TELEVISIONS/GET_TELEVISIONS_FAIL"

export const GET_TELEVISION_REQUEST = "TELEVISIONS/GET_TELEVISION_REQUEST"
export const GET_TELEVISION_SUCCESS = "TELEVISIONS/GET_TELEVISION_SUCCESS"
export const GET_TELEVISION_FAIL = "TELEVISIONS/GET_TELEVISION_FAIL"

export const SET_FILTERS_REQUEST = "TELEVISIONS/SET_FILTERS_REQUEST"
export const SET_FILTERS_SUCCESS = "TELEVISIONS/SET_FILTERS_SUCCESS"

export const FILTER_REQUEST = "TELEVISIONS/FILTER_REQUEST"
export const FILTER_SUCCESS = "TELEVISIONS/FILTER_SUCCESS"

export const SET_PRICE_RANGE_REQUEST = "TELEVISIONS/SET_PRICE_RANGE_REQUEST"
export const SET_PRICE_RANGE_SUCCESS = "TELEVISIONS/SET_PRICE_RANGE_SUCCESS"

/* for TABLETS */
export const GET_TABLETS_REQUEST = "TABLETS/GET_TABLETS_REQUEST"
export const GET_TABLETS_SUCCESS = "TABLETS/GET_TABLETS_SUCCESS"
export const GET_TABLETS_FAIL = "TABLETS/GET_TABLETS_FAIL"

export const GET_TABLET_REQUEST = "TABLETS/GET_TABLET_REQUEST"
export const GET_TABLET_SUCCESS = "TABLETS/GET_TABLET_SUCCESS"
export const GET_TABLET_FAIL = "TABLETS/GET_TABLET_FAIL"

export const TABLETS_SET_FILTERS_REQUEST = "TABLETS/SET_FILTERS_REQUEST"
export const TABLETS_SET_FILTERS_SUCCESS = "TABLETS/SET_FILTERS_SUCCESS"

export const TABLETS_FILTER_REQUEST = "TABLETS/FILTER_REQUEST"
export const TABLETS_FILTER_SUCCESS = "TABLETS/FILTER_SUCCESS"

export const TABLETS_SET_PRICE_RANGE_REQUEST = "TABLETS/SET_PRICE_RANGE_REQUEST"
export const TABLETS_SET_PRICE_RANGE_SUCCESS = "TABLETS/SET_PRICE_RANGE_SUCCESS"

/* for ERROR */
export const ERROR_SHOW = "ERRORS/ERROR_SHOW"
export const ERROR_HIDE = "ERRORS/ERROR_SHOW"