/* for TELEVISIONS */
export const GET_TELEVISIONS_REQUEST = "TELEVISIONS/GET_TELEVISIONS_REQUEST"
export const GET_TELEVISIONS_SUCCESS = "TELEVISIONS/GET_TELEVISIONS_SUCCESS"

export const GET_TELEVISION_REQUEST = "TELEVISIONS/GET_TELEVISION_REQUEST"
export const GET_TELEVISION_SUCCESS = "TELEVISIONS/GET_TELEVISION_SUCCESS"

export const SET_FILTERS = "TELEVISIONS/SET_FILTERS"
export const FILTER = "TELEVISIONS/FILTER"