/* for TELEVISIONS */
export const GET_TELEVISIONS_REQUEST = "TELEVISIONS/GET_TELEVISIONS_REQUEST"
export const GET_TELEVISIONS_SUCCESS = "TELEVISIONS/GET_TELEVISIONS_SUCCESS"

export const GET_TELEVISION_REQUEST = "TELEVISIONS/GET_TELEVISION_REQUEST"
export const GET_TELEVISION_SUCCESS = "TELEVISIONS/GET_TELEVISION_SUCCESS"

export const SET_FILTERS_REQUEST = "TELEVISIONS/SET_FILTERS_REQUEST"
export const SET_FILTERS_SUCCESS = "TELEVISIONS/SET_FILTERS_SUCCESS"

export const FILTER_REQUEST = "TELEVISIONS/FILTER_REQUEST"
export const FILTER_SUCCESS = "TELEVISIONS/FILTER_SUCCESS"

export const SET_PRICE_RANGE_REQUEST = "TELEVISIONS/SET_PRICE_RANGE_REQUEST"
export const SET_PRICE_RANGE_SUCCESS = "TELEVISIONS/SET_PRICE_RANGE_SUCCESS"